spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pgdb:5432/mydatabase
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
